name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.1.0'

      - name: Install dependencies
        run: npm install  # 依存関係をインストール

      - name: Run ESLint
        run: npm run lint:es  # ESLintを実行

      - name: Run Stylelint
        run: npm run lint:style  # Stylelintを実行

      - name: Run lintfix
        run: npm run lint:fix  # Fixを実行
